jobs:
  - job: Build_Windows
    pool:
      vmImage: windows-latest
    steps:
      - powershell: |
            Set-PSRepository PSGallery -InstallationPolicy Trusted
            Install-Module PSPublishModule -ErrorAction Stop -Force -Verbose
            .\Build\BuildModule.ps1
        displayName: "Run Pester Tests - PowerShell 5"
      - pwsh: |
            Set-PSRepository PSGallery -InstallationPolicy Trusted
            Install-Module PSPublishModule -ErrorAction Stop -Force -Verbose
            .\Build\BuildModule.ps1
        displayName: "Run Pester Tests - PowerShell 7+"

  - job: Build_PSCore_Ubuntu1604
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: UseDotNet@2
          inputs:
            version: '6.x'
      - script: |
          curl -sSL https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/microsoft-prod.list
          curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo tee /etc/apt/trusted.gpg.d/microsoft.asc
          sudo apt-get update
          sudo apt-get install -y powershell
        displayName: "Install PowerShell Core"
      - pwsh: |
            Set-PSRepository PSGallery -InstallationPolicy Trusted
            Install-Module PSPublishModule -ErrorAction Stop -Force -Verbose
            .\Build\BuildModule.ps1
        displayName: "Run Pester Tests"

  - job: Build_PSCore_MacOS1013
    pool:
      vmImage: macOS-latest
    steps:
      - script: |
          brew update
          brew tap caskroom/cask
          brew install mono-libgdiplus
          brew install --cask powershell
        displayName: "Install PowerShell Core"
      - pwsh: |
            Set-PSRepository PSGallery -InstallationPolicy Trusted
            Install-Module PSPublishModule -ErrorAction Stop -Force -Verbose
            .\Build\BuildModule.ps1
        displayName: "Run Pester Tests"
