# PSPGP bootstrapper
# Auto-generated by PowerForge. Do not edit.

# PowerForge script preamble begin

# PowerForge script preamble end


$PowerForgeDevelopmentBinaryLoaded = $false
# Source development binary loader
$PowerForgeDevelopmentBinaryRoot = [IO.Path]::GetFullPath([IO.Path]::Combine($PSScriptRoot, 'Sources', 'PSPGP', 'bin'))
$PowerForgeDevelopmentBinaryMode = 'Environment'
$PowerForgeDevelopmentBinaryEnvironmentVariable = 'PSPGP_DEVELOPMENT'
$PowerForgeDevelopmentConfigurationEnvironmentVariable = 'PSPGP_DEVELOPMENT_CONFIGURATION'
$PowerForgeDevelopmentCoreFrameworks = @('netstandard2.0', 'net472')
$PowerForgeDevelopmentDesktopFrameworks = @('net472', 'netstandard2.0')
$PowerForgeDevelopmentUseAssemblyLoadContext = $true
$PowerForgeDevelopmentEnabled = $false
if ($PowerForgeDevelopmentBinaryMode -eq 'Auto') {
    $PowerForgeDevelopmentEnabled = $true
} elseif ($PowerForgeDevelopmentBinaryMode -eq 'Environment') {
    $PowerForgeDevelopmentRequestedValue = [Environment]::GetEnvironmentVariable($PowerForgeDevelopmentBinaryEnvironmentVariable)
    $PowerForgeDevelopmentEnabled = [string]::Equals($PowerForgeDevelopmentRequestedValue, 'true', [StringComparison]::OrdinalIgnoreCase)
}

if ($PowerForgeDevelopmentEnabled) {
    $PowerForgeDevelopmentConfigurations = @()
    $PowerForgeDevelopmentRequestedConfiguration = [Environment]::GetEnvironmentVariable($PowerForgeDevelopmentConfigurationEnvironmentVariable)
    if (-not [string]::IsNullOrWhiteSpace($PowerForgeDevelopmentRequestedConfiguration)) {
        $PowerForgeDevelopmentConfigurations += $PowerForgeDevelopmentRequestedConfiguration
    }
    $PowerForgeDevelopmentConfigurations += 'Debug'
    $PowerForgeDevelopmentConfigurations += 'Release'
    $PowerForgeDevelopmentConfigurations = @($PowerForgeDevelopmentConfigurations | Where-Object { -not [string]::IsNullOrWhiteSpace($_) } | Select-Object -Unique)

    $PowerForgeDevelopmentFrameworks = if ($PSEdition -eq 'Core') { $PowerForgeDevelopmentCoreFrameworks } else { $PowerForgeDevelopmentDesktopFrameworks }
    $PowerForgeDevelopmentBinaryPath = $null
    foreach ($PowerForgeDevelopmentConfiguration in $PowerForgeDevelopmentConfigurations) {
        foreach ($PowerForgeDevelopmentFramework in $PowerForgeDevelopmentFrameworks) {
            $PowerForgeDevelopmentCandidate = [IO.Path]::Combine($PowerForgeDevelopmentBinaryRoot, $PowerForgeDevelopmentConfiguration, $PowerForgeDevelopmentFramework, 'PSPGP.dll')
            if (Test-Path -LiteralPath $PowerForgeDevelopmentCandidate) {
                $PowerForgeDevelopmentBinaryPath = $PowerForgeDevelopmentCandidate
                break
            }
        }
        if ($PowerForgeDevelopmentBinaryPath) { break }
    }

    if ($PowerForgeDevelopmentBinaryPath) {
        try {
            $ImportModule = Get-Command -Name Import-Module -Module Microsoft.PowerShell.Core

            if ($PSEdition -eq 'Core' -and $PowerForgeDevelopmentUseAssemblyLoadContext) {
                if (-not ('PSPGP.DevelopmentModuleLoadContext.ModuleAssemblyLoadContext' -as [type])) {
                    Add-Type -TypeDefinition @'
using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Runtime.Loader;

namespace PSPGP.DevelopmentModuleLoadContext
{
    public sealed class ModuleAssemblyLoadContext : AssemblyLoadContext
    {
        private static readonly object Sync = new object();
        private static readonly Dictionary<string, ModuleAssemblyLoadContext> Contexts = new Dictionary<string, ModuleAssemblyLoadContext>(StringComparer.OrdinalIgnoreCase);

        private readonly string _assemblyDirectory;
        private readonly string _moduleAssemblyPath;
        private readonly AssemblyDependencyResolver _resolver;
        private Assembly _moduleAssembly;

        private ModuleAssemblyLoadContext(string moduleAssemblyPath, string contextName)
            : base(contextName, isCollectible: false)
        {
            _moduleAssemblyPath = Path.GetFullPath(moduleAssemblyPath);
            _assemblyDirectory = Path.GetDirectoryName(_moduleAssemblyPath) ?? string.Empty;
            _resolver = TryCreateResolver(_moduleAssemblyPath);
        }

        public static Assembly LoadModule(string moduleAssemblyPath, string contextName)
        {
            if (string.IsNullOrWhiteSpace(moduleAssemblyPath))
                throw new ArgumentException("Module assembly path is required.", nameof(moduleAssemblyPath));

            var fullPath = Path.GetFullPath(moduleAssemblyPath);
            if (!File.Exists(fullPath))
                throw new FileNotFoundException("Module assembly was not found.", fullPath);

            lock (Sync)
            {
                ModuleAssemblyLoadContext context;
                if (!Contexts.TryGetValue(fullPath, out context))
                {
                    context = new ModuleAssemblyLoadContext(fullPath, string.IsNullOrWhiteSpace(contextName) ? Path.GetFileNameWithoutExtension(fullPath) : contextName);
                    Contexts[fullPath] = context;
                }

                return context.LoadMainModule();
            }
        }

        protected override Assembly Load(AssemblyName assemblyName)
        {
            if (assemblyName == null || string.IsNullOrWhiteSpace(assemblyName.Name))
                return null;

            var loaderAssembly = typeof(ModuleAssemblyLoadContext).Assembly.GetName();
            if (AssemblyName.ReferenceMatchesDefinition(loaderAssembly, assemblyName))
                return typeof(ModuleAssemblyLoadContext).Assembly;

            var resolvedPath = _resolver?.ResolveAssemblyToPath(assemblyName);
            if (!string.IsNullOrWhiteSpace(resolvedPath) && File.Exists(resolvedPath))
                return LoadFromAssemblyPath(resolvedPath);

            var assemblyPath = Path.Combine(_assemblyDirectory, assemblyName.Name + ".dll");
            return File.Exists(assemblyPath) ? LoadFromAssemblyPath(assemblyPath) : null;
        }

        protected override IntPtr LoadUnmanagedDll(string unmanagedDllName)
        {
            var resolvedPath = _resolver?.ResolveUnmanagedDllToPath(unmanagedDllName);
            if (!string.IsNullOrWhiteSpace(resolvedPath) && File.Exists(resolvedPath))
                return LoadUnmanagedDllFromPath(resolvedPath);

            return IntPtr.Zero;
        }

        private static AssemblyDependencyResolver TryCreateResolver(string assemblyPath)
        {
            try
            {
                return new AssemblyDependencyResolver(assemblyPath);
            }
            catch (InvalidOperationException)
            {
                return null;
            }
        }

        private Assembly LoadMainModule()
        {
            if (_moduleAssembly == null)
                _moduleAssembly = LoadFromAssemblyPath(_moduleAssemblyPath);

            return _moduleAssembly;
        }
    }
}
'@ -Language CSharp -ErrorAction Stop
                }
                $PowerForgeDevelopmentModuleAssembly = [PSPGP.DevelopmentModuleLoadContext.ModuleAssemblyLoadContext]::LoadModule($PowerForgeDevelopmentBinaryPath, 'PSPGP.Development')
                $PowerForgeDevelopmentInnerModule = & $ImportModule -Assembly $PowerForgeDevelopmentModuleAssembly -Force -PassThru -ErrorAction Stop

                if ($PowerForgeDevelopmentInnerModule) {
                    # Import-Module -Assembly loads the inner binary module into its own module object. PowerShell has no
                    # public API to copy those exported cmdlets back to the script-module wrapper, so this uses the same
                    # private PSModuleInfo hook used by community ALC loaders.
                    $AddExportedCmdlet = [System.Management.Automation.PSModuleInfo].GetMethod(
                        'AddExportedCmdlet',
                        [System.Reflection.BindingFlags]'Instance, NonPublic'
                    )
                    $PowerForgeOuterModule = $ExecutionContext.SessionState.Module
                    $PowerForgeIsModuleWrapper = $false
                    if ($null -ne $PowerForgeOuterModule -and
                        -not [string]::IsNullOrWhiteSpace($PowerForgeOuterModule.Path) -and
                        -not [string]::IsNullOrWhiteSpace($PSCommandPath)) {
                        try {
                            [StringComparison] $PowerForgePathComparison = & {
                                param([string] $PowerForgeProbePath)

                                # Case behavior belongs to the containing filesystem. Windows can opt individual
                                # directories into case sensitivity, while macOS volumes may be case-insensitive.
                                # Inspect existing names without requiring write access; ambiguity fails closed.
                                try {
                                    $PowerForgeProbeDirectory = [IO.Path]::GetDirectoryName([IO.Path]::GetFullPath($PowerForgeProbePath))
                                    $PowerForgeNames = New-Object 'System.Collections.Generic.HashSet[string]' ([StringComparer]::Ordinal)
                                    foreach ($PowerForgeEntry in [IO.Directory]::EnumerateFileSystemEntries($PowerForgeProbeDirectory)) {
                                        [void] $PowerForgeNames.Add([IO.Path]::GetFileName($PowerForgeEntry))
                                    }

                                    foreach ($PowerForgeName in $PowerForgeNames) {
                                        foreach ($PowerForgeAlternateName in @($PowerForgeName.ToUpperInvariant(), $PowerForgeName.ToLowerInvariant())) {
                                            if ([string]::Equals($PowerForgeName, $PowerForgeAlternateName, [StringComparison]::Ordinal) -or
                                                $PowerForgeNames.Contains($PowerForgeAlternateName)) {
                                                continue
                                            }

                                            $PowerForgeAlternatePath = [IO.Path]::Combine($PowerForgeProbeDirectory, $PowerForgeAlternateName)
                                            if ([IO.File]::Exists($PowerForgeAlternatePath) -or [IO.Directory]::Exists($PowerForgeAlternatePath)) {
                                                return [StringComparison]::OrdinalIgnoreCase
                                            }

                                            return [StringComparison]::Ordinal
                                        }
                                    }
                                } catch {
                                    # Ordinal comparison prevents an uncertain probe from exporting into a caller.
                                }

                                return [StringComparison]::Ordinal
                            } $PSCommandPath
                            $PowerForgeIsModuleWrapper = [string]::Equals(
                                [IO.Path]::GetFullPath($PowerForgeOuterModule.Path),
                                [IO.Path]::GetFullPath($PSCommandPath),
                                $PowerForgePathComparison
                            )
                        } catch {
                            $PowerForgeIsModuleWrapper = $false
                        }
                    }
                    if (-not $PowerForgeIsModuleWrapper) {
                        # A Script/ScriptPacked entry point, including one dot-sourced by another module, must not mutate
                        # that caller's export table. The imported inner module's commands remain available to this script.
                    } elseif ($null -ne $AddExportedCmdlet) {
                        foreach ($Cmd in $PowerForgeDevelopmentInnerModule.ExportedCmdlets.Values) {
                            $AddExportedCmdlet.Invoke($PowerForgeOuterModule, @(, $Cmd)) | Out-Null
                        }
                        $AddExportedAlias = [System.Management.Automation.PSModuleInfo].GetMethod(
                            'AddExportedAlias',
                            [System.Reflection.BindingFlags]'Instance, NonPublic'
                        )
                        if ($null -ne $AddExportedAlias) {
                            foreach ($Alias in $PowerForgeDevelopmentInnerModule.ExportedAliases.Values) {
                                $AliasTarget = if ([string]::IsNullOrWhiteSpace($Alias.Definition)) { $Alias.ResolvedCommandName } else { $Alias.Definition }
                                try {
                                    # The alias must exist in this module scope before the private export table can reference it.
                                    Set-Alias -Name $Alias.Name -Value $AliasTarget -Scope Local -Force -ErrorAction Stop
                                    $ExportedAlias = $ExecutionContext.SessionState.InvokeCommand.GetCommand($Alias.Name, [System.Management.Automation.CommandTypes]::Alias)
                                    if ($null -ne $ExportedAlias) {
                                        $AddExportedAlias.Invoke($PowerForgeOuterModule, @(, $ExportedAlias)) | Out-Null
                                    } else {
                                        Write-Warning -Message "Alias '$($Alias.Name)' from PSPGP was created but could not be resolved for export."
                                    }
                                } catch {
                                    Write-Warning -Message "Alias '$($Alias.Name)' from PSPGP could not be re-exported: $($_.Exception.Message)"
                                }
                            }
                        } else {
                            Write-Warning -Message "AddExportedAlias is not available on this PowerShell version. Aliases from PSPGP will not be re-exported to the module scope."
                        }
                    } else {
                        Write-Warning -Message "AddExportedCmdlet is not available on this PowerShell version. Falling back to direct Import-Module; cmdlets from PSPGP will load from the default context."
                        & $ImportModule $PowerForgeDevelopmentBinaryPath -ErrorAction Stop
                    }
                }

            } else {
                $PowerForgeDevelopmentLoadedType = 'PSPGP.Initialize' -as [type]
                $PowerForgeDevelopmentLoadedAssembly = if ($PowerForgeDevelopmentLoadedType -and $PowerForgeDevelopmentLoadedType.Assembly) { $PowerForgeDevelopmentLoadedType.Assembly } else { $null }
                $PowerForgeDevelopmentLoadedAssemblyPath = if ($PowerForgeDevelopmentLoadedAssembly -and -not [string]::IsNullOrWhiteSpace($PowerForgeDevelopmentLoadedAssembly.Location)) { [IO.Path]::GetFullPath($PowerForgeDevelopmentLoadedAssembly.Location) } else { $null }
                $PowerForgeDevelopmentSelectedBinaryPath = [IO.Path]::GetFullPath($PowerForgeDevelopmentBinaryPath)
                if ($PowerForgeDevelopmentLoadedAssembly -and [string]::Equals($PowerForgeDevelopmentLoadedAssemblyPath, $PowerForgeDevelopmentSelectedBinaryPath, [StringComparison]::OrdinalIgnoreCase)) {
                    & $ImportModule -Assembly $PowerForgeDevelopmentLoadedType.Assembly -Force -ErrorAction Stop
                } else {
                    & $ImportModule $PowerForgeDevelopmentBinaryPath -ErrorAction Stop
                }
            }

            $PowerForgeDevelopmentBinaryLoaded = $true
        } catch {
            if ($ErrorActionPreference -eq 'Stop') {
                throw
            } else {
                Write-Warning -Message "Importing development binary $PowerForgeDevelopmentBinaryPath failed. Falling back to packaged loader when available. Error: $($_.Exception.Message)"
            }
        }
    }
}

# PowerForge script payload begin

# PowerForge script payload end
$FunctionsToExport = @()
$CmdletsToExport = @('Get-PGPInspect', 'Get-PGPKey', 'Get-PGPKeyInfo', 'New-PGPKey', 'Protect-PGP', 'Test-PGP', 'Unprotect-PGP')
$AliasesToExport = @()
Export-ModuleMember -Function $FunctionsToExport -Alias $AliasesToExport -Cmdlet $CmdletsToExport
