<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Company>Evotec</Company>
        <Authors>Przemyslaw Klys</Authors>
        <VersionPrefix>1.0.0</VersionPrefix>
        <TargetFrameworks>net472;netstandard2.0;net8.0</TargetFrameworks>
        <AssemblyName>PSPGP</AssemblyName>
        <Copyright>(c) 2011 - 2025 Przemyslaw Klys @ Evotec. All rights reserved.</Copyright>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
        <PackageReference Include="PgpCore" Version="7.0.0" />
        <PackageReference Include="PowerShellStandard.Library" Version="5.1.1" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup Condition=" '$(TargetFramework)' == 'net472' ">
        <Reference Include="System.Net.Http" />
    </ItemGroup>

    <PropertyGroup Condition=" '$(TargetFramework)' == 'net472' ">
        <DefineConstants>$(DefineConstants);FRAMEWORK</DefineConstants>
    </PropertyGroup>

    <!-- We need to remove PowerShell conflicting libraries as it will break output -->
    <Target Name="RemoveFilesAfterBuild" AfterTargets="Build">
        <Delete Files="$(OutDir)System.Management.Automation.dll" />
        <Delete Files="$(OutDir)System.Management.dll" />
    </Target>

    <!-- Make sure the output DLL's from library are included in the output -->
    <PropertyGroup>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    </PropertyGroup>

    <PropertyGroup>
        <!-- This is needed for XmlDoc2CmdletDoc to generate a PowerShell documentation file. -->
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <!-- This is needed for XmlDoc2CmdletDoc to generate a PowerShell documentation file. -->
    <ItemGroup>
        <PackageReference Include="MatejKafka.XmlDoc2CmdletDoc" Version="0.6.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <!-- Copy help documentation to publish output after publish -->
    <Target Name="CopyHelpDocumentationToPublishOutput" AfterTargets="Publish">
        <Copy SourceFiles="$(OutputPath)$(AssemblyName).dll-Help.xml"
            DestinationFiles="$(PublishDir)$(AssemblyName).dll-Help.xml"
            Condition="Exists('$(OutputPath)$(AssemblyName).dll-Help.xml')" />
    </Target>

</Project>
